---
# - hosts: all
- hosts: all
  sudo: true
  tasks:
  - name: ensure apt-transport-https is installed
    apt:
      pkg: "apt-transport-https"
      state: installed
  
  - name: add docker repo gpg key
    apt_key:
      id: "58118E89F3A912897C070ADBF76221572C52609D"
      keyserver: "hkp://pgp.mit.edu:80"
      state: present
  
  - name: add docker repo and update apt cache
    apt_repository:
      #repo: "https://apt.dockerproject.org/repo debian-jessie main"
      repo: "deb https://apt.dockerproject.org/repo ubuntu-trusty main"
      update_cache: yes
      state: present
  
  - name: install docker-engine
    apt:
      pkg: "docker-engine"
      state: installed
      
  - name: install pip
    apt:
      pkg: "{{ item }}"
      state: installed
    with_items:
      - python-dev
      - python-pip
      - python-virtualenv
  
  - name: install docker-py
    pip:
      name: docker-py
      virtualenv: /opt/venv
      virtualenv_command: virtualenv
  
  - name: make sure docker is running
    service:
      name: docker
      state: started
