# install first the ansible plugin:
# $ vagrant plugin install ansible
VAGRANTFILE_API_VERSION= "2"
MACHINE_HOSTNAME = "ansible"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :private_network, ip: "10.100.100.2"

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--name", MACHINE_HOSTNAME]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--memory", 512]
    v.customize ["modifyvm", :id, "--cpus", 1]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "./playbooks/docker.yml"
    ansible.sudo = true
    ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
  end

  config.vm.define MACHINE_HOSTNAME do |machine|
    machine.vm.hostname = MACHINE_HOSTNAME
  end

end
